-- 11Eleven · supabase/seed.sql — catálogo de equipos FC 27 (115 clubes)
-- Generado desde src/convex/footballData.ts · idempotente.
-- El ON CONFLICT (name) exige unicidad: aseguramos el índice aquí.
create unique index if not exists team_catalog_name_uq on public.team_catalog (name);
insert into public.team_catalog (name, league, country, color_primary, color_secondary)
values
  ('Manchester City', 'Premier League', 'Inglaterra', '#6CABDD', '#1C2C5B'),
  ('Arsenal FC', 'Premier League', 'Inglaterra', '#EF0107', '#063672'),
  ('Liverpool FC', 'Premier League', 'Inglaterra', '#C8102E', '#00B2A9'),
  ('Aston Villa', 'Premier League', 'Inglaterra', '#670E36', '#95BFE5'),
  ('Tottenham Hotspur', 'Premier League', 'Inglaterra', '#132257', '#FFFFFF'),
  ('Chelsea FC', 'Premier League', 'Inglaterra', '#034694', '#DBA111'),
  ('Newcastle United', 'Premier League', 'Inglaterra', '#241F20', '#FFFFFF'),
  ('Manchester United', 'Premier League', 'Inglaterra', '#DA291C', '#FBE122'),
  ('West Ham United', 'Premier League', 'Inglaterra', '#7A263A', '#1BB1E7'),
  ('Brighton & Hove Albion', 'Premier League', 'Inglaterra', '#0057B8', '#FFFFFF'),
  ('Wolverhampton', 'Premier League', 'Inglaterra', '#FDB913', '#231F20'),
  ('Fulham FC', 'Premier League', 'Inglaterra', '#000000', '#FFFFFF'),
  ('Bournemouth', 'Premier League', 'Inglaterra', '#DA291C', '#000000'),
  ('Brentford FC', 'Premier League', 'Inglaterra', '#E30613', '#FFB81C'),
  ('Crystal Palace', 'Premier League', 'Inglaterra', '#1B458F', '#C4122E'),
  ('Nottingham Forest', 'Premier League', 'Inglaterra', '#DD0000', '#FFFFFF'),
  ('Everton FC', 'Premier League', 'Inglaterra', '#003399', '#FFFFFF'),
  ('Ipswich Town', 'Premier League', 'Inglaterra', '#0044AA', '#FFFFFF'),
  ('Leicester City', 'Premier League', 'Inglaterra', '#003090', '#FFFFFF'),
  ('Southampton FC', 'Premier League', 'Inglaterra', '#D71920', '#FFFFFF'),
  ('Real Madrid CF', 'LaLiga', 'España', '#FEBE10', '#00529F'),
  ('FC Barcelona', 'LaLiga', 'España', '#A50044', '#004D98'),
  ('Atlético Madrid', 'LaLiga', 'España', '#CE3524', '#FFFFFF'),
  ('Athletic Bilbao', 'LaLiga', 'España', '#EE2523', '#FFFFFF'),
  ('Real Sociedad', 'LaLiga', 'España', '#003DA5', '#FFFFFF'),
  ('Real Betis', 'LaLiga', 'España', '#00954C', '#FFFFFF'),
  ('Villarreal CF', 'LaLiga', 'España', '#FFE114', '#005B8E'),
  ('Sevilla FC', 'LaLiga', 'España', '#D40D26', '#FFFFFF'),
  ('Valencia CF', 'LaLiga', 'España', '#EE3524', '#000000'),
  ('RC Celta', 'LaLiga', 'España', '#8AC3EE', '#FFFFFF'),
  ('Getafe CF', 'LaLiga', 'España', '#004FA3', '#FFFFFF'),
  ('CA Osasuna', 'LaLiga', 'España', '#D91A21', '#003DA5'),
  ('RCD Mallorca', 'LaLiga', 'España', '#E20613', '#000000'),
  ('Rayo Vallecano', 'LaLiga', 'España', '#E53027', '#FFFFFF'),
  ('UD Almería', 'LaLiga', 'España', '#E53027', '#FFFFFF'),
  ('Las Palmas', 'LaLiga', 'España', '#FFD700', '#00529F'),
  ('Inter de Milán', 'Serie A', 'Italia', '#0068A8', '#0A0A0A'),
  ('AC Milan', 'Serie A', 'Italia', '#FB090B', '#000000'),
  ('Juventus FC', 'Serie A', 'Italia', '#000000', '#FFFFFF'),
  ('SSC Napoli', 'Serie A', 'Italia', '#12A0D7', '#FFFFFF'),
  ('AS Roma', 'Serie A', 'Italia', '#8E1F2F', '#F0BC42'),
  ('SS Lazio', 'Serie A', 'Italia', '#87D8F7', '#FFFFFF'),
  ('Atalanta BC', 'Serie A', 'Italia', '#1E71B8', '#000000'),
  ('ACF Fiorentina', 'Serie A', 'Italia', '#5B2C8A', '#FFFFFF'),
  ('Torino FC', 'Serie A', 'Italia', '#8B0000', '#FFFFFF'),
  ('Bologna FC', 'Serie A', 'Italia', '#1A2B5C', '#FFFFFF'),
  ('US Lecce', 'Serie A', 'Italia', '#FFD700', '#000000'),
  ('Genoa CFC', 'Serie A', 'Italia', '#8B0000', '#FFFFFF'),
  ('Udinese Calcio', 'Serie A', 'Italia', '#000000', '#FFFFFF'),
  ('Cagliari Calcio', 'Serie A', 'Italia', '#8B0000', '#0044AA'),
  ('Hellas Verona', 'Serie A', 'Italia', '#0044AA', '#FFD700'),
  ('US Sassuolo', 'Serie A', 'Italia', '#00A850', '#000000'),
  ('Bayern de Múnich', 'Bundesliga', 'Alemania', '#DC052D', '#0066B2'),
  ('Borussia Dortmund', 'Bundesliga', 'Alemania', '#FDE100', '#000000'),
  ('Bayer Leverkusen', 'Bundesliga', 'Alemania', '#E32221', '#000000'),
  ('RB Leipzig', 'Bundesliga', 'Alemania', '#DD0741', '#FFFFFF'),
  ('Eintracht Frankfurt', 'Bundesliga', 'Alemania', '#E1000F', '#000000'),
  ('VfB Stuttgart', 'Bundesliga', 'Alemania', '#E32219', '#FFFFFF'),
  ('VfL Wolfsburg', 'Bundesliga', 'Alemania', '#65B32E', '#000000'),
  ('SC Freiburg', 'Bundesliga', 'Alemania', '#000000', '#FFFFFF'),
  ('Borussia Mönchengladbach', 'Bundesliga', 'Alemania', '#18A950', '#000000'),
  ('Werder Bremen', 'Bundesliga', 'Alemania', '#1D9053', '#FFFFFF'),
  ('Paris Saint-Germain', 'Ligue 1', 'Francia', '#004170', '#DA291C'),
  ('Olympique de Marsella', 'Ligue 1', 'Francia', '#2FAEE0', '#FFFFFF'),
  ('Olympique Lyonnais', 'Ligue 1', 'Francia', '#004DA0', '#FFFFFF'),
  ('AS Monaco', 'Ligue 1', 'Francia', '#E7192D', '#FFFFFF'),
  ('Lille OSC', 'Ligue 1', 'Francia', '#E3001B', '#FFFFFF'),
  ('OGC Nice', 'Ligue 1', 'Francia', '#E30613', '#000000'),
  ('Stade Rennais', 'Ligue 1', 'Francia', '#E30613', '#000000'),
  ('RC Lens', 'Ligue 1', 'Francia', '#FFD700', '#E30613'),
  ('RC Strasbourg', 'Ligue 1', 'Francia', '#009FE3', '#FFFFFF'),
  ('Toulouse FC', 'Ligue 1', 'Francia', '#7B2D8B', '#FFFFFF'),
  ('FC Porto', 'Liga Portugal', 'Portugal', '#003893', '#FFFFFF'),
  ('SL Benfica', 'Liga Portugal', 'Portugal', '#FF0000', '#FFFFFF'),
  ('Sporting CP', 'Liga Portugal', 'Portugal', '#00843D', '#FFFFFF'),
  ('SC Braga', 'Liga Portugal', 'Portugal', '#E30613', '#FFFFFF'),
  ('AFC Ajax', 'Eredivisie', 'Países Bajos', '#D2122E', '#FFFFFF'),
  ('PSV Eindhoven', 'Eredivisie', 'Países Bajos', '#ED1C24', '#FFFFFF'),
  ('Feyenoord Rotterdam', 'Eredivisie', 'Países Bajos', '#EE3124', '#FFFFFF'),
  ('AZ Alkmaar', 'Eredivisie', 'Países Bajos', '#E30613', '#FFFFFF'),
  ('Galatasaray SK', 'Süper Lig', 'Turquía', '#FFD700', '#E30613'),
  ('Fenerbahçe SK', 'Süper Lig', 'Turquía', '#002D87', '#FFD700'),
  ('Beşiktaş JK', 'Süper Lig', 'Turquía', '#000000', '#FFFFFF'),
  ('River Plate', 'Liga Profesional', 'Argentina', '#FFFFFF', '#E30613'),
  ('Boca Juniors', 'Liga Profesional', 'Argentina', '#003DA5', '#FFD700'),
  ('Racing Club', 'Liga Profesional', 'Argentina', '#6CB4EE', '#FFFFFF'),
  ('San Lorenzo', 'Liga Profesional', 'Argentina', '#003DA5', '#E30613'),
  ('Estudiantes LP', 'Liga Profesional', 'Argentina', '#E30613', '#FFFFFF'),
  ('Vélez Sarsfield', 'Liga Profesional', 'Argentina', '#FFFFFF', '#003DA5'),
  ('Flamengo', 'Brasileirão', 'Brasil', '#E30613', '#000000'),
  ('Palmeiras', 'Brasileirão', 'Brasil', '#006437', '#FFFFFF'),
  ('Corinthians', 'Brasileirão', 'Brasil', '#000000', '#FFFFFF'),
  ('São Paulo FC', 'Brasileirão', 'Brasil', '#E30613', '#000000'),
  ('Santos FC', 'Brasileirão', 'Brasil', '#000000', '#FFFFFF'),
  ('Internacional', 'Brasileirão', 'Brasil', '#E30613', '#FFFFFF'),
  ('Grêmio', 'Brasileirão', 'Brasil', '#0068A8', '#FFFFFF'),
  ('Club América', 'Liga MX', 'México', '#FFD700', '#004B8D'),
  ('Chivas de Guadalajara', 'Liga MX', 'México', '#E30613', '#FFFFFF'),
  ('Cruz Azul', 'Liga MX', 'México', '#004B8D', '#FFFFFF'),
  ('Tigres UANL', 'Liga MX', 'México', '#FFD700', '#004B8D'),
  ('CF Monterrey', 'Liga MX', 'México', '#004B8D', '#FFFFFF'),
  ('Al-Hilal SFC', 'Saudi Pro League', 'Arabia Saudita', '#004B8D', '#FFFFFF'),
  ('Al-Ahli SFC', 'Saudi Pro League', 'Arabia Saudita', '#006838', '#FFFFFF'),
  ('Al-Nassr FC', 'Saudi Pro League', 'Arabia Saudita', '#FFD700', '#004B8D'),
  ('Al-Ittihad Club', 'Saudi Pro League', 'Arabia Saudita', '#FFD700', '#000000'),
  ('Millonarios FC', 'Liga BetPlay', 'Colombia', '#004B8D', '#FFFFFF'),
  ('Atlético Nacional', 'Liga BetPlay', 'Colombia', '#006838', '#FFFFFF'),
  ('Independiente Santa Fe', 'Liga BetPlay', 'Colombia', '#E30613', '#FFFFFF'),
  ('América de Cali', 'Liga BetPlay', 'Colombia', '#E30613', '#FFFFFF'),
  ('Junior FC', 'Liga BetPlay', 'Colombia', '#E30613', '#004B8D'),
  ('Inter Miami CF', 'MLS', 'Estados Unidos', '#F5B6CD', '#000000'),
  ('LA Galaxy', 'MLS', 'Estados Unidos', '#00245D', '#FFD700'),
  ('New York City FC', 'MLS', 'Estados Unidos', '#6CACE4', '#00205B'),
  ('Kawasaki Frontale', 'J1 League', 'Japón', '#003DA5', '#000000'),
  ('Yokohama F. Marinos', 'J1 League', 'Japón', '#003DA5', '#FFFFFF')
on conflict (name) do update set
  league = excluded.league,
  country = excluded.country,
  color_primary = excluded.color_primary,
  color_secondary = excluded.color_secondary;
