import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { AVAILABILITIES, AVAILABILITY_META, formatMoney, } from "@/convex/rulesEngine";
import { useNavigate, useOutletContext } from "react-router";
import { SectionCard } from "@/components/eleven/SectionCard";
import { AvailabilityBadge, PlayerAvatar, PositionPill } from "@/components/eleven/PlayerBits";
import { useSquadActions } from "@/hooks/use-squad-actions";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue, } from "@/components/ui/select";
import { Button } from "@/components/ui/button";
import { Info, Shirt, Users } from "lucide-react";
import { cn } from "@/lib/utils";
export default function PlayerStatus() {
    const state = useOutletContext();
    const navigate = useNavigate();
    const { saveAvailability, savingAvailability } = useSquadActions();
    const stats = state.stats;
    if (!stats)
        return null;
    return (_jsxs("div", { className: "mx-auto flex w-full max-w-[1400px] flex-col gap-5", children: [_jsxs("header", { className: "flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between", children: [_jsxs("div", { children: [_jsx("h1", { className: "display text-2xl", children: "Estado de jugadores" }), _jsxs("p", { className: "mt-1 max-w-3xl text-sm text-muted-foreground", children: ["La situaci\u00F3n que marques en cada jugador es exactamente lo que ver\u00E1n los dem\u00E1s Presidentes cuando abran la plantilla de ", state.club?.name, ". Cada estado incluye icono, texto y color: nunca se comunica solo con color."] })] }), _jsxs("div", { className: "flex flex-wrap gap-2", children: [_jsxs(Button, { type: "button", variant: "outline", className: "min-h-11", onClick: () => navigate("/dashboard/club/plantilla"), children: [_jsx(Users, { className: "size-4", "aria-hidden": "true" }), "Ver plantilla"] }), _jsxs(Button, { type: "button", className: "min-h-11", onClick: () => navigate("/dashboard/formacion"), children: [_jsx(Shirt, { className: "size-4", "aria-hidden": "true" }), "Formaci\u00F3n"] })] })] }), _jsx("section", { "aria-label": "Leyenda de situaciones", className: "grid gap-3 sm:grid-cols-2 xl:grid-cols-4", children: AVAILABILITIES.map((option) => {
                    const meta = AVAILABILITY_META[option];
                    return (_jsxs("div", { className: "card-soft flex flex-col gap-2 p-4", children: [_jsxs("div", { className: "flex items-center justify-between gap-2", children: [_jsx(AvailabilityBadge, { availability: option }), _jsx("span", { className: "num display text-lg", children: state.availability[option] })] }), _jsx("p", { className: "text-xs leading-relaxed text-muted-foreground", children: meta.description })] }, option));
                }) }), _jsx(SectionCard, { title: "Gestiona la situaci\u00F3n de tu plantilla", icon: Users, bodyClassName: "p-0", children: _jsx("ul", { className: "divide-y", children: state.squad.map((player) => (_jsxs("li", { className: cn("flex flex-col gap-3 p-3 sm:flex-row sm:items-center sm:gap-4", savingAvailability && "opacity-80"), children: [_jsxs("div", { className: "flex min-w-0 flex-1 items-center gap-3", children: [_jsx(PlayerAvatar, { name: player.name, flag: player.flag, group: player.group, size: "sm", photo: player.photo }), _jsxs("div", { className: "min-w-0", children: [_jsx("p", { className: "truncate text-sm font-semibold", children: player.name }), _jsxs("p", { className: "flex items-center gap-1.5 truncate text-[11px] text-muted-foreground", children: [_jsx(PositionPill, { position: player.position, group: player.group }), player.nationality, " \u00B7 ", player.age, " a\u00F1os \u00B7 ", formatMoney(player.value)] })] })] }), _jsxs("div", { className: "flex items-center gap-3 sm:justify-end", children: [_jsx(AvailabilityBadge, { availability: player.availability, showLabel: false, className: "sm:hidden" }), _jsxs(Select, { value: player.availability, disabled: savingAvailability, onValueChange: (next) => saveAvailability(player.playerId, next, player.name), children: [_jsx(SelectTrigger, { className: "min-h-11 w-full sm:w-[230px]", "aria-label": `Situación de ${player.name}`, children: _jsx(SelectValue, {}) }), _jsx(SelectContent, { children: AVAILABILITIES.map((option) => (_jsxs(SelectItem, { value: option, className: "min-h-11", children: [_jsx("span", { "aria-hidden": "true", className: "mr-2", children: AVAILABILITY_META[option].symbol }), AVAILABILITY_META[option].label] }, option))) })] })] })] }, player.squadPlayerId))) }) }), _jsxs("p", { className: "flex items-start gap-2 rounded-lg border bg-muted/30 p-3 text-xs leading-relaxed text-muted-foreground", children: [_jsx(Info, { className: "mt-0.5 size-3.5 shrink-0", "aria-hidden": "true" }), "Solo puedes gestionar jugadores de tu propia plantilla (", stats.size, " jugadores). El motor de reglas impide cualquier operaci\u00F3n que rompa el reglamento del torneo y registra cada cambio en la auditor\u00EDa."] })] }));
}
